---
# tasks file for apache

- hosts: webservers
  tasks:
  - name: installation du serveur apache
    yum:
      name: "{{ item }}"
      state: present
    loop:
      - httpd
      - nano
      - epel-release 
